apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  virtualhost:
    fqdn: 'gitops.devozs.com'
    tls:
      secretName: wildcard-devozs-com
  routes:
    - conditions:
        - prefix: /
      services:
        - name: ikit-frontend
          port: 3000