apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: ikit-frontend
  namespace: ikit
spec:
  virtualhost:
    fqdn: 'ikit.devozs.com'
    tls:
      secretName: wildcard-devozs-com
  routes:
    - conditions:
        - prefix: /
      services:
        - name: ikit-frontend
          port: 3000