apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: blog-frontend
  namespace: blog
spec:
  virtualhost:
    fqdn: 'blog.devozs.com'
    tls:
      secretName: wildcard-devozs-com
  routes:
    - conditions:
        - prefix: /
      services:
        - name: blog-frontend
          port: 3000