apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: blog-frontend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: blog-frontend
  filterTags:
    pattern: RELEASE_PLACEHOLDER
    extract: '$ts'
  policy:
    numerical:
      order: asc

