apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-frontend
  namespace: blog
  labels:
    app: blog-frontend
spec:
  selector:
    matchLabels:
      app: blog-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: blog-frontend
    spec:
      imagePullSecrets:
        - name: cr-secret
      containers:
        - name: blog-frontend
          image: blog-frontend:TAG
          imagePullPolicy: Always
          ports:
            - name: http-prom
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: blog-frontend
  namespace: blog
spec:
  selector:
    app: blog-frontend
  ports:
    - port: 3000
      name: blog-frontend
